from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(5, 1, 841, 741))
        self.graphicsView.setObjectName("graphicsView")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(870, 10, 321, 711))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 319, 898))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_size = QtWidgets.QLabel(self.groupBox)
        self.label_size.setObjectName("label_size")
        self.horizontalLayout_11.addWidget(self.label_size)
        self.spinBox_size = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_size.setObjectName("spinBox_size")
        self.spinBox_size.setValue(20)
        self.horizontalLayout_11.addWidget(self.spinBox_size)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.pushButton_set_default = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_set_default.setObjectName("pushButton_set_default")
        self.verticalLayout.addWidget(self.pushButton_set_default)
        self.gridLayout_10.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_radius_o = QtWidgets.QLabel(self.groupBox_3)
        self.label_radius_o.setAlignment(QtCore.Qt.AlignCenter)
        self.label_radius_o.setObjectName("label_radius_o")
        self.horizontalLayout_13.addWidget(self.label_radius_o)
        self.spinBox_radius_o = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_radius_o.setSuffix("")
        self.spinBox_radius_o.setPrefix("")
        self.spinBox_radius_o.setObjectName("spinBox_radius_o")
        self.horizontalLayout_13.addWidget(self.spinBox_radius_o)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_3, 3, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_9.setContentsMargins(2, -1, 2, -1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_rotation_x = QtWidgets.QLabel(self.groupBox_4)
        self.label_rotation_x.setObjectName("label_rotation_x")
        self.horizontalLayout_12.addWidget(self.label_rotation_x)
        self.spinBox_rotation_x = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_rotation_x.setSuffix("")
        self.spinBox_rotation_x.setPrefix("")
        self.spinBox_rotation_x.setObjectName("spinBox_rotation_x")
        self.horizontalLayout_12.addWidget(self.spinBox_rotation_x)
        self.gridLayout_9.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_rotation_y = QtWidgets.QLabel(self.groupBox_4)
        self.label_rotation_y.setObjectName("label_rotation_y")
        self.horizontalLayout_14.addWidget(self.label_rotation_y)
        self.spinBox_rotation_y = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_rotation_y.setSuffix("")
        self.spinBox_rotation_y.setPrefix("")
        self.spinBox_rotation_y.setObjectName("spinBox_rotation_y")
        self.horizontalLayout_14.addWidget(self.spinBox_rotation_y)
        self.gridLayout_9.addLayout(self.horizontalLayout_14, 0, 1, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_rotation_angle = QtWidgets.QLabel(self.groupBox_4)
        self.label_rotation_angle.setObjectName("label_rotation_angle")
        self.horizontalLayout_15.addWidget(self.label_rotation_angle)
        self.spinBox_rotation_angle = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_rotation_angle.setSuffix("")
        self.spinBox_rotation_angle.setPrefix("")
        self.spinBox_rotation_angle.setObjectName("spinBox_rotation_angle")
        self.horizontalLayout_15.addWidget(self.spinBox_rotation_angle)
        self.gridLayout_9.addLayout(self.horizontalLayout_15, 0, 2, 1, 1)
        self.pushButton_rotation_apply = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_rotation_apply.setEnabled(True)
        self.pushButton_rotation_apply.setObjectName("pushButton_rotation_apply")
        self.gridLayout_9.addWidget(self.pushButton_rotation_apply, 1, 0, 1, 3)
        self.gridLayout_10.addWidget(self.groupBox_4, 4, 0, 1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setContentsMargins(2, 6, 2, 2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_affine_xx = QtWidgets.QLabel(self.groupBox_6)
        self.label_affine_xx.setObjectName("label_affine_xx")
        self.horizontalLayout_44.addWidget(self.label_affine_xx)
        self.spinBox_affine_xx = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_affine_xx.setSuffix("")
        self.spinBox_affine_xx.setPrefix("")
        self.spinBox_affine_xx.setObjectName("spinBox_affine_xx")
        # self.spinBox_affine_xx.setMaximum(1000)  ####### !!!!!!!!!!!!
        self.horizontalLayout_44.addWidget(self.spinBox_affine_xx)
        self.gridLayout_7.addLayout(self.horizontalLayout_44, 0, 0, 1, 1)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_affine_yx = QtWidgets.QLabel(self.groupBox_6)
        self.label_affine_yx.setObjectName("label_affine_yx")
        self.horizontalLayout_46.addWidget(self.label_affine_yx)
        self.spinBox_affine_yx = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_affine_yx.setSuffix("")
        self.spinBox_affine_yx.setPrefix("")
        self.spinBox_affine_yx.setObjectName("spinBox_affine_yx")
        self.horizontalLayout_46.addWidget(self.spinBox_affine_yx)
        self.gridLayout_7.addLayout(self.horizontalLayout_46, 1, 0, 1, 1)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_affine_0y = QtWidgets.QLabel(self.groupBox_6)
        self.label_affine_0y.setObjectName("label_affine_0y")
        self.horizontalLayout_48.addWidget(self.label_affine_0y)
        self.spinBox_affine_0y = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_affine_0y.setSuffix("")
        self.spinBox_affine_0y.setPrefix("")
        self.spinBox_affine_0y.setObjectName("spinBox_affine_0y")
        self.horizontalLayout_48.addWidget(self.spinBox_affine_0y)
        self.gridLayout_7.addLayout(self.horizontalLayout_48, 2, 1, 1, 1)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_affine_yy = QtWidgets.QLabel(self.groupBox_6)
        self.label_affine_yy.setObjectName("label_affine_yy")
        self.horizontalLayout_47.addWidget(self.label_affine_yy)
        self.spinBox_49 = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_49.setSuffix("")
        self.spinBox_49.setPrefix("")
        self.spinBox_49.setObjectName("spinBox_49")
        self.horizontalLayout_47.addWidget(self.spinBox_49)
        self.gridLayout_7.addLayout(self.horizontalLayout_47, 1, 1, 1, 1)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_affine_xy = QtWidgets.QLabel(self.groupBox_6)
        self.label_affine_xy.setObjectName("label_affine_xy")
        self.horizontalLayout_45.addWidget(self.label_affine_xy)
        self.spinBox_affine_xy = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_affine_xy.setSuffix("")
        self.spinBox_affine_xy.setPrefix("")
        self.spinBox_affine_xy.setObjectName("spinBox_affine_xy")
        self.horizontalLayout_45.addWidget(self.spinBox_affine_xy)
        self.gridLayout_7.addLayout(self.horizontalLayout_45, 0, 1, 1, 1)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_affine_0x = QtWidgets.QLabel(self.groupBox_6)
        self.label_affine_0x.setObjectName("label_affine_0x")
        self.horizontalLayout_49.addWidget(self.label_affine_0x)
        self.spinBox_affine_0x = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_affine_0x.setSuffix("")
        self.spinBox_affine_0x.setPrefix("")
        self.spinBox_affine_0x.setObjectName("spinBox_affine_0x")
        self.horizontalLayout_49.addWidget(self.spinBox_affine_0x)
        self.gridLayout_7.addLayout(self.horizontalLayout_49, 2, 0, 1, 1)
        self.pushButton_affine_apply = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_affine_apply.setObjectName("pushButton_affine_apply")
        self.gridLayout_7.addWidget(self.pushButton_affine_apply, 3, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_8.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.label_perspective_0y = QtWidgets.QLabel(self.groupBox_7)
        self.label_perspective_0y.setObjectName("label_perspective_0y")
        self.horizontalLayout_55.addWidget(self.label_perspective_0y)
        self.spinBox_perspective_0y = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinBox_perspective_0y.setSuffix("")
        self.spinBox_perspective_0y.setPrefix("")
        self.spinBox_perspective_0y.setObjectName("spinBox_perspective_0y")
        self.horizontalLayout_55.addWidget(self.spinBox_perspective_0y)
        self.gridLayout_8.addLayout(self.horizontalLayout_55, 2, 1, 1, 1)
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_perspective_wy = QtWidgets.QLabel(self.groupBox_7)
        self.label_perspective_wy.setObjectName("label_perspective_wy")
        self.horizontalLayout_54.addWidget(self.label_perspective_wy)
        self.spinBox_perspective_wy = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinBox_perspective_wy.setSuffix("")
        self.spinBox_perspective_wy.setPrefix("")
        self.spinBox_perspective_wy.setObjectName("spinBox_perspective_wy")
        self.horizontalLayout_54.addWidget(self.spinBox_perspective_wy)
        self.gridLayout_8.addLayout(self.horizontalLayout_54, 1, 2, 1, 1)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.label_perspective_w0 = QtWidgets.QLabel(self.groupBox_7)
        self.label_perspective_w0.setObjectName("label_perspective_w0")
        self.horizontalLayout_56.addWidget(self.label_perspective_w0)
        self.spinBox_perspective_w0 = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinBox_perspective_w0.setSuffix("")
        self.spinBox_perspective_w0.setPrefix("")
        self.spinBox_perspective_w0.setObjectName("spinBox_perspective_w0")
        self.horizontalLayout_56.addWidget(self.spinBox_perspective_w0)
        self.gridLayout_8.addLayout(self.horizontalLayout_56, 2, 2, 1, 1)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.label_perspective_wx = QtWidgets.QLabel(self.groupBox_7)
        self.label_perspective_wx.setObjectName("label_perspective_wx")
        self.horizontalLayout_57.addWidget(self.label_perspective_wx)
        self.spinBox_perspective_wx = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinBox_perspective_wx.setSuffix("")
        self.spinBox_perspective_wx.setPrefix("")
        self.spinBox_perspective_wx.setObjectName("spinBox_perspective_wx")
        self.horizontalLayout_57.addWidget(self.spinBox_perspective_wx)
        self.gridLayout_8.addLayout(self.horizontalLayout_57, 0, 2, 1, 1)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.label_perspective_0x = QtWidgets.QLabel(self.groupBox_7)
        self.label_perspective_0x.setObjectName("label_perspective_0x")
        self.horizontalLayout_52.addWidget(self.label_perspective_0x)
        self.spinBox_perspective_0x = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinBox_perspective_0x.setSuffix("")
        self.spinBox_perspective_0x.setPrefix("")
        self.spinBox_perspective_0x.setObjectName("spinBox_perspective_0x")
        self.horizontalLayout_52.addWidget(self.spinBox_perspective_0x)
        self.gridLayout_8.addLayout(self.horizontalLayout_52, 2, 0, 1, 1)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_perspective_yx = QtWidgets.QLabel(self.groupBox_7)
        self.label_perspective_yx.setObjectName("label_perspective_yx")
        self.horizontalLayout_50.addWidget(self.label_perspective_yx)
        self.spinBox_perspective_yx = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinBox_perspective_yx.setSuffix("")
        self.spinBox_perspective_yx.setPrefix("")
        self.spinBox_perspective_yx.setObjectName("spinBox_perspective_yx")
        self.horizontalLayout_50.addWidget(self.spinBox_perspective_yx)
        self.gridLayout_8.addLayout(self.horizontalLayout_50, 1, 0, 1, 1)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_perspective_yy = QtWidgets.QLabel(self.groupBox_7)
        self.label_perspective_yy.setObjectName("label_perspective_yy")
        self.horizontalLayout_53.addWidget(self.label_perspective_yy)
        self.spinBox_perspective_yy = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinBox_perspective_yy.setSuffix("")
        self.spinBox_perspective_yy.setPrefix("")
        self.spinBox_perspective_yy.setObjectName("spinBox_perspective_yy")
        self.horizontalLayout_53.addWidget(self.spinBox_perspective_yy)
        self.gridLayout_8.addLayout(self.horizontalLayout_53, 1, 1, 1, 1)
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.label_perspective_xy = QtWidgets.QLabel(self.groupBox_7)
        self.label_perspective_xy.setObjectName("label_perspective_xy")
        self.horizontalLayout_58.addWidget(self.label_perspective_xy)
        self.spinBox_60 = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinBox_60.setSuffix("")
        self.spinBox_60.setPrefix("")
        self.spinBox_60.setObjectName("spinBox_60")
        self.horizontalLayout_58.addWidget(self.spinBox_60)
        self.gridLayout_8.addLayout(self.horizontalLayout_58, 0, 1, 1, 1)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_perspective_xx = QtWidgets.QLabel(self.groupBox_7)
        self.label_perspective_xx.setObjectName("label_perspective_xx")
        self.horizontalLayout_51.addWidget(self.label_perspective_xx)
        self.spinBox_perspective_xx = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinBox_perspective_xx.setSuffix("")
        self.spinBox_perspective_xx.setPrefix("")
        self.spinBox_perspective_xx.setObjectName("spinBox_perspective_xx")
        self.horizontalLayout_51.addWidget(self.spinBox_perspective_xx)
        self.gridLayout_8.addLayout(self.horizontalLayout_51, 0, 0, 1, 1)
        self.pushButton_apply_perspective = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_apply_perspective.setObjectName("pushButton_apply_perspective")
        self.gridLayout_8.addWidget(self.pushButton_apply_perspective, 3, 0, 1, 3)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        self.gridLayout_10.addWidget(self.groupBox_5, 5, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(5, 6, 5, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")

        self.pushButton_length_apply = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_length_apply.setObjectName("Apply")
        self.pushButton_length_apply.setText("Apply")
        self.horizontalLayout_9.addWidget(self.pushButton_length_apply)
        self.gridLayout.addLayout(self.horizontalLayout_9, 4, 1, 1, 1)

        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_length_fg = QtWidgets.QLabel(self.groupBox_2)
        self.label_length_fg.setObjectName("label_length_fg")
        self.horizontalLayout_6.addWidget(self.label_length_fg)
        self.spinBox_length_fg = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_length_fg.setSuffix("")
        self.spinBox_length_fg.setPrefix("")
        self.spinBox_length_fg.setObjectName("spinBox_length_fg")
        self.horizontalLayout_6.addWidget(self.spinBox_length_fg)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 1, 1, 1)


        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_length_bc = QtWidgets.QLabel(self.groupBox_2)
        self.label_length_bc.setObjectName("label_length_bc")
        self.horizontalLayout_2.addWidget(self.label_length_bc)
        self.spinBox_length_bc = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_length_bc.setSuffix("")
        self.spinBox_length_bc.setPrefix("")
        self.spinBox_length_bc.setObjectName("spinBox_length_bc")
        self.horizontalLayout_2.addWidget(self.spinBox_length_bc)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)


        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_length_cd = QtWidgets.QLabel(self.groupBox_2)
        self.label_length_cd.setObjectName("label_length_cd")
        self.horizontalLayout_3.addWidget(self.label_length_cd)
        self.spinBox_length_cd = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_length_cd.setSuffix("")
        self.spinBox_length_cd.setPrefix("")
        self.spinBox_length_cd.setObjectName("spinBox_length_cd")
        self.horizontalLayout_3.addWidget(self.spinBox_length_cd)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)



        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_length_de = QtWidgets.QLabel(self.groupBox_2)
        self.label_length_de.setObjectName("label_length_de")
        self.horizontalLayout_4.addWidget(self.label_length_de)
        self.spinBox_length_de = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_length_de.setSuffix("")
        self.spinBox_length_de.setPrefix("")
        self.spinBox_length_de.setObjectName("spinBox_length_de")
        self.horizontalLayout_4.addWidget(self.spinBox_length_de)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)

        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_length_gh = QtWidgets.QLabel(self.groupBox_2)
        self.label_length_gh.setObjectName("label_length_gh")
        self.horizontalLayout_10.addWidget(self.label_length_gh)
        self.spinBox_length_gh = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_length_gh.setSuffix("")
        self.spinBox_length_gh.setPrefix("")
        self.spinBox_length_gh.setObjectName("spinBox_length_gh")
        self.horizontalLayout_10.addWidget(self.spinBox_length_gh)
        self.gridLayout.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)

        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_length_hi = QtWidgets.QLabel(self.groupBox_2)
        self.label_length_hi.setObjectName("label_length_hi")
        self.horizontalLayout_7.addWidget(self.label_length_hi)
        self.spinBox_length_hi = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_length_hi.setSuffix("")
        self.spinBox_length_hi.setPrefix("")
        self.spinBox_length_hi.setObjectName("spinBox_length_hi")
        self.horizontalLayout_7.addWidget(self.spinBox_length_hi)
        self.gridLayout.addLayout(self.horizontalLayout_7, 3, 1, 1, 1)

        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_length_ef = QtWidgets.QLabel(self.groupBox_2)
        self.label_length_ef.setObjectName("label_length_ef")
        self.horizontalLayout_5.addWidget(self.label_length_ef)
        self.spinBox_length_ef = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_length_ef.setSuffix("")
        self.spinBox_length_ef.setPrefix("")
        self.spinBox_length_ef.setObjectName("spinBox_length_ef")
        self.horizontalLayout_5.addWidget(self.spinBox_length_ef)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)

        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_length_ia = QtWidgets.QLabel(self.groupBox_2)
        self.label_length_ia.setObjectName("label_length_ia")
        self.horizontalLayout_8.addWidget(self.label_length_ia)
        self.spinBox_length_ia = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_length_ia.setSuffix("")
        self.spinBox_length_ia.setPrefix("")
        self.spinBox_length_ia.setObjectName("spinBox_length_ia")
        self.horizontalLayout_8.addWidget(self.spinBox_length_ia)
        self.gridLayout.addLayout(self.horizontalLayout_8, 4, 0, 1, 1)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_length_ab = QtWidgets.QLabel(self.groupBox_2)
        self.label_length_ab.setObjectName("label_length_ab")
        self.horizontalLayout.addWidget(self.label_length_ab)
        self.spinBox_length_ab = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_length_ab.setSuffix("")
        self.spinBox_length_ab.setPrefix("")
        self.spinBox_length_ab.setProperty("value", 10)
        self.spinBox_length_ab.setObjectName("spinBox_length_ab")
        self.horizontalLayout.addWidget(self.spinBox_length_ab)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.gridLayout_10.addWidget(self.groupBox_2, 2, 0, 1, 2)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        for attr in vars(self):
            if 'spinBox' in attr:
                getattr(self, attr).setMaximum(1000)
        self.spinBox_length_ab.setValue(50)
        self.spinBox_length_bc.setValue(50)
        self.spinBox_length_cd.setValue(10)
        self.spinBox_length_de.setValue(20)
        self.spinBox_length_ef.setValue(150)
        self.spinBox_length_fg.setValue(20)
        self.spinBox_length_gh.setValue(55)
        self.spinBox_length_hi.setValue(55)
        self.spinBox_length_ia.setValue(20)



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Pixels per cm"))
        self.label_size.setText(_translate("MainWindow", "px/cm"))
        self.pushButton_set_default.setText(_translate("MainWindow", "Set Default Figure"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Radius"))
        self.label_radius_o.setText(_translate("MainWindow", "O"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Rotation"))
        self.label_rotation_x.setText(_translate("MainWindow", "x"))
        self.label_rotation_y.setText(_translate("MainWindow", "y"))
        self.label_rotation_angle.setText(_translate("MainWindow", "α‎˚"))
        self.pushButton_rotation_apply.setText(_translate("MainWindow", "Apply"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Transformation"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Affine"))
        self.label_affine_xx.setText(_translate("MainWindow", "Xx"))
        self.label_affine_yx.setText(_translate("MainWindow", "Yx"))
        self.label_affine_0y.setText(_translate("MainWindow", "0y"))
        self.label_affine_yy.setText(_translate("MainWindow", "Yy"))
        self.label_affine_xy.setText(_translate("MainWindow", "Xy"))
        self.label_affine_0x.setText(_translate("MainWindow", "0x"))
        self.pushButton_affine_apply.setText(_translate("MainWindow", "Apply"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Perspective"))
        self.label_perspective_0y.setText(_translate("MainWindow", "0y"))
        self.label_perspective_wy.setText(_translate("MainWindow", "wY"))
        self.label_perspective_w0.setText(_translate("MainWindow", "w0"))
        self.label_perspective_wx.setText(_translate("MainWindow", "wX"))
        self.label_perspective_0x.setText(_translate("MainWindow", "0x"))
        self.label_perspective_yx.setText(_translate("MainWindow", "Yx"))
        self.label_perspective_yy.setText(_translate("MainWindow", "Yy"))
        self.label_perspective_xy.setText(_translate("MainWindow", "Xy"))
        self.label_perspective_xx.setText(_translate("MainWindow", "Xx"))
        self.pushButton_apply_perspective.setText(_translate("MainWindow", "Apply"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Length"))
        self.label_length_fg.setText(_translate("MainWindow", "FG"))
        self.label_length_cd.setText(_translate("MainWindow", "CD"))
        self.label_length_bc.setText(_translate("MainWindow", "BC"))
        self.label_length_de.setText(_translate("MainWindow", "DE"))
        self.label_length_gh.setText(_translate("MainWindow", "GH"))
        self.label_length_hi.setText(_translate("MainWindow", "HI"))
        self.label_length_ef.setText(_translate("MainWindow", "EF"))
        self.label_length_ia.setText(_translate("MainWindow", "IA"))
        self.label_length_ab.setText(_translate("MainWindow", "AB"))


